name: Tests

on:
  pull_request:
    branches: [main]

jobs:
  plugins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.13"
      - name: Plugin Validation
        run: python3 scripts/validate-plugins.py
