name: Tests

on:
  pull_request:
    branches: [main]

jobs:
  plugins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.13"
      - name: Plugin Validation
        run: python3 scripts/validate-plugins.py
